### PR TITLE
update to use "standard" deploy template

### PR DESCRIPTION
**Pull request by tkellen**
This deployment setup is based on the work @cowboy did building a standard deploy template for nest-applicants. It's pretty close in functionality to what @ajpiano did already, but it has a few nice things added.

I'm honestly not sure what the issue with the previous setup was, I just figured this would be a good opportunity to test out our template and it works very well.

There is an extensive README that covers how this works in the deploy folder, but the command you probably care about is just this:
`deploy/deploy.sh commit=master`

If you omit `commit=master`, it will deploy from master automatically. The only reason I mention it is to show that it's possible to deploy the site from a branch. What is currently live is the deployment branch.

### CODE REVIEW

**Comment by tkellen** [comment]
Also, this adds a new command `npm run build` which can be run on initial checkout to build the site (this is what the playbooks use after checking out the repo).

**Comment by cowboy** [comment]
@tkellen are you sure `deploy/deploy.sh` actually works? You seem to be using the newest bash script, but you're not following the newest naming convention, which is `PLAYBOOK_NAME-INVENTORY_NAME.sh`.

See the [relevant code](https://github.com/bocoup/johnny-five.org/blob/aa47b74f56fe9b299751accfcf8fd82c560ec7c8/deploy/provision.sh#L9-L12).

**Comment by tkellen** [comment]
Yup, it's working here. I removed a few things since there is no staging environment on this.

**Comment by cowboy** [comment]
Weird. I have no idea how the code you've committed can work.

**Comment by tkellen** [comment]
I renamed the deploy scripts. Somehow or another it's able to accept an inventory file as a folder.  Not sure what the semantics around that are--not going to dig into it now.

**Comment by tkellen** [comment]
The resulting command was:
```
Running command: cd "/Users/tkellen/code/johnny-five.org/deploy/ansible" && ansible-playbook -i inventory/ deploy.yml
```

**Comment by cowboy** [comment]
Ok, hopefully it's choosing the `deploy` inventory and not the `provision` inventory and the current behavior doesn't change. Good luck!

**Comment by cowboy** [comment]
This probably works because there's only one file in the inventory folder. Hopefully that never changes!

**Comment by rwaldron** [comment]
@cowboy or it can be fixed/changed?

**Comment by tkellen** [comment]
I pushed a fix @rwaldron, we're good!

**Pull request merged**
