### PR TITLE
[wip] Include home link to the logo

### PR DESCRIPTION
**Pull request by leobalter**
Fixes gh-36

cc @Wilto 

It's not that simple...  WIP

### CODE REVIEW

**Comment by leobalter** [comment]
still wip, if you fix it, go ahead and discard this PR

**Comment by rwaldron** [comment]
- needs to be done on all tpl/* pages have this link
- needs to not wreck the layout

**Comment by leobalter** [comment]
done

**Comment by leobalter** [comment]
already fixed at d040984

**Pull request closed without merging**
